### ISSUE TITLE
Improve docs on app state

### ISSUE THREAD

**Issue by shapiromatron** [kkinder/puepy-mkdocs#3]
This project looks awesome, I'm excited to try it out on a few projects we're working on.

One question I had though after reading through the docs. A common pattern we use in our web apps is a single state store, and then multiple components can read/write to the state store, with components being updated reactively. In JS, we use [mobx](https://mobx.js.org/), though there other other libraries that accomplish something similar. 

Is this pattern possible with puepy? It's seems better than passing state up/down the component tree. I didn't see any examples that explored this concept, though maybe I was missing it.

**Comment by kkinder** [comment]
I added some docs here:

https://docs.puepy.dev/guide/reactivity/#application-state

They could be better, but for now I think this at least helps some.
